version: '3.9'

services:
  pfchrs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID}
        http_proxy: ${HTTP_PROXY}
    image: local/pfchrs
    container_name: pfchrs
    volumes:
      - ./pfchrs:/app
    command: /start-reload.sh
    environment:
      MAX_WORKERS: 1
      SESSION_USERNAME: localuser
    ports:
      - "2025:2025"
    networks:
      local:
    deploy:
      resources:
        # shm_size: 512M
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  local:
